### ISSUE TITLE
key error in f_within_prior in SFM-PAR notebook

### ISSUE THREAD

**Issue by coreyabshire** [AlexAndorra/advanced-gp-pydata#2]
Thanks for the video and repo! Just wanted to report a slight problem I hit when I was walking through the SFM-PAR notebook. In the cell under **Prior GPs** that starts with `f_within_prior = idata.prior["f_within"]` I was getting an error along the lines of:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[27], line 15
     10 f_long_prior_aligned = f_long_prior.sel(
     11     season=unique_combinations["season_nbr"].to_numpy()
--snip--
KeyError: "'gameday' is not a valid dimension or coordinate for Dataset with dimensions FrozenMappingWarningOnValuesAccess({'chain': 1, 'draw': 500, 'f_within_dim_0': 38})"
```

even though I created the conda environment from the provided yaml. I wasn't able to pinpoint the exact cause, but suspect a recent PyMC release changed something that impacted it. The environment file specified >= 5.16.0 which I think was getting me 5.19.0. But I noticed in your watermark near the end of the video you were using 5.17.0, and when I pinned to that version the problem went away and the rest of the notebook ran fine.

**Comment by AlexAndorra** [comment]
Good catch @coreyabshire , and thanks for reporting!

That's indeed because 5.19.0 changed the kwarg in the `prior` method from `gp_dims` to `dims`. That's fixed and pushed. I also pinned PyMC to >= 5.19.0 in the env file

PyMCheers 🖖
